### ISSUE TITLE
[스파르타코딩클럽] 알고보면 알기쉬운 알고리즘 - 1주차

### ISSUE THREAD

**Issue by south-daria** [south-daria/algorithm_example#1]
https://www.notion.so/1-9c4497df09324035a3f3e212f7a43f94#c05a07d68d2b48868917e6b01a1adef4

시간/공간 복잡도 판단하기

**Comment by jynam821** [comment]
for-else문 - for문이 끝날 때까지 break를 하지않으면 else문 실행.
is_alpha() - 알파벳이면 true를 반환
ord() - ascii 코드로 변환하는 함수
chr() - ascii -> char

**Comment by jynam821** [comment]
최댓값 찾기 
-이중 for문 도면서 비교하는 방법
-처음 최댓값 지정후 for문 돌면서 비교하는 방법

**Comment by jynam821** [comment]
시간복잡도
공간복잡도
: 시간복잡도>공간복잡도 (알고리즘상 중요도)
점근표기법
빅오 표기법: 최악의 시나리오
오메가 표기법: 최선의 시나리오

**Comment by jynam821** [comment]
소수 나열하기

-주어진 자연수 N이 소수이기 위한 필요충분 조건은 N이 N의 제곱근보다 크지 않은 어떤 소수로도 나눠지지 않음. 
수가 수를 나누면 몫이 발생하게 되는데 몫과 나누는 수, 둘 중 하나는 반드시 N의 제곱근 이하임.
이를 이용해서 i * i ≤ n 일 때까지만 비교하면 됨.
